trigger:
  - master
pool:
  vmImage: 'ubuntu-latest' 
variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: "-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)"
steps:
  - task: Cache@2
    inputs:
      key: 'maven | "$(Agent.OS)" | **/pom.xml'
      restoreKeys: |
        maven | "$(Agent.OS)"
        maven
      path: $(MAVEN_CACHE_FOLDER)
    displayName: Cache Maven local repo
 
  - task: Bash@3
    inputs:
      targetType: "inline"
      script: |        
        pwd         
        export BUILD_NUMBER=$(Build.BuildNumber)
        echo 'build number  #'${BUILD_NUMBER}

        sudo -- sh -c "echo '60.250.171.28    wsapear-rw-istio-system.apps.ocp.iisi.test' >> /etc/hosts"
        
        timedatectl
        echo 'set timezone to Asia/Taipei'
        sudo timedatectl set-timezone Asia/Taipei
        timedatectl

        echo 'inspect docker daemon'
        cat /etc/docker/daemon.json
        sudo systemctl restart docker
        sudo systemctl daemon-reload
    displayName: "set env"
    continueOnError: true  #This code in self-hosted agent  will be 

  - script: 'mkdir -p $(System.DefaultWorkingDirectory)/artifacts'
    displayName: 'create artifacts directory'

  # - template: template-mvn-default.yml
  #   parameters:
  #     param: 
  #       - default
  # - script: 'mvn clean package'
  #   displayName: 'mvn package'
  
  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'deploy'
      options: '-Dmaven.test.skip=true  --settings settings.xml   -DaltDeploymentRepository=CHT_WildFly::default::https://pkgs.dev.azure.com/iisiD210641-a/CHT_WildFly/_packaging/CHT_WildFly/maven/v1'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '8'
      mavenVersionOption: 'Default'
      mavenOptions: '-Xmx3072m  $(MAVEN_OPTS)'
      mavenAuthenticateFeed: true
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
      checkStyleRunAnalysis: false # replaced by sonarqube
      pmdRunAnalysis: false # PMD does not support jdk11
      findBugsRunAnalysis: false #Findbugs does not support jdk11
      javadoc: true

  - template: template-mvn-nest-deploy.yml
    parameters:
        param: 
          - bookws_client 
          - GeneratedWebServiceClients

  - template: nest-template.yml
    parameters:
        param: 
          - bookws_client 

  - task: PublishPipelineArtifact@1
    continueOnError: true    
    inputs:
      targetPath:  '$(System.DefaultWorkingDirectory)/artifacts' 
      parallel: true
    displayName: 'uploading artifacts'  


